api-version: 1.16
name: OVTribes
version: 1.0
author: OnlyVanilla
website: www.onlyvanilla.org
main: org.onlyvanilla.ovtribes.Main
description: OVTribes Commands
commands:
    tribes:
        description: Create tribes
        usage: /tribes create
    claimsponges:
        description: Claim a sponge reward
        usage: /claimsponges
    setsponges:
        description: Set sponge reward
        usage: /setsponges [player] [amount]
        permission: tribes.setsponges
    addsponges:
        description: Ad sponge reward
        usage: /addsponges [player] [amount]
        permission: tribes.addsponges