api-version: 1.16
name: OVTribes
version: 1.0
author: OnlyVanilla
website: www.onlyvanilla.org
main: org.onlyvanilla.ovtribes.Main
description: OVTribes Commands
commands:
    tribes:
        description: Create tribes
        usage: /tribes create